/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.*;
import SonidoEImagen.Imagen;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author a22victorlr
 */
public class UI extends javax.swing.JFrame {

    public void pintarEn(JLabel label) {
        mapaPanel.add(label);
        mapaPanel.setComponentZOrder(label, 1);
        label.setOpaque(true);

        mapaPanel.repaint();
    }

    private Timer temporizador;
    private Juego partida;
    UI interfaz;
    private int sec = 0;
    private int minute;

    /**
     * Creates new form UI
     */
    public UI() {
        
        interfaz = this;
        initComponents();
        partida = new Juego(this);
        colocarImagenes();
        mapaPanel.setVisible(false);
        batallaPanel.setVisible(false);
        eventoPanel.setVisible(false);
        Iniciar.setVisible(true);
        Iniciar.repaint();
    }

    private void colocarImagenes() {
        //Strings de dirección
        String menuDirec = SonidoEImagen.Imagen.getImageLink("Menu");
        String evtDirec = SonidoEImagen.Imagen.getImageLink("Evento");
        String batallaDirec = SonidoEImagen.Imagen.getImageLink("Batalla");
        String mapaDirec = SonidoEImagen.Imagen.getImageLink("Mapa");
        String inicDirec = SonidoEImagen.Imagen.getImageLink("Inicio");

        ImageIcon menu = new ImageIcon(menuDirec);
        ImageIcon menuRedimen = Imagen.redimensionarimagen(menu, menuLabel.getWidth(), menuLabel.getHeight());
        this.menuLabel.setIcon(menuRedimen);

        ImageIcon evento = new ImageIcon(evtDirec);
        ImageIcon eventoRedimen = Imagen.redimensionarimagen(evento, eventoLabel.getWidth(), eventoLabel.getHeight());
        this.eventoLabel.setIcon(eventoRedimen);

        ImageIcon batalla = new ImageIcon(batallaDirec);
        ImageIcon batallaRedimen = Imagen.redimensionarimagen(batalla, batallaLabel.getWidth(), batallaLabel.getHeight());
        this.batallaLabel.setIcon(batallaRedimen);

        ImageIcon mapa = new ImageIcon(mapaDirec);
        ImageIcon mapaRedimen = Imagen.redimensionarimagen(mapa, mapaLabel.getWidth(), mapaLabel.getHeight());
        this.mapaLabel.setIcon(mapaRedimen);

        ImageIcon inic = new ImageIcon(inicDirec);
        ImageIcon inicRedimen = Imagen.redimensionarimagen(inic, Iniciar.getWidth(), Iniciar.getHeight());
        this.Iniciar.setIcon(inicRedimen);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        Iniciar = new javax.swing.JButton();
        menuLabel = new javax.swing.JLabel();
        mapaPanel = new javax.swing.JPanel();
        mapaLabel = new javax.swing.JLabel();
        timerP = new javax.swing.JLabel();
        eventoPanel = new javax.swing.JPanel();
        eventoLabel = new javax.swing.JLabel();
        batallaPanel = new javax.swing.JPanel();
        batallaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(816, 639));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel.setBackground(new java.awt.Color(60, 3, 65));
        menuPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        Iniciar.setOpaque(true);
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mapaPanel.setBackground(new java.awt.Color(60, 63, 5));
        mapaPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mapaPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        timerP.setText("00:00");

        javax.swing.GroupLayout mapaPanelLayout = new javax.swing.GroupLayout(mapaPanel);
        mapaPanel.setLayout(mapaPanelLayout);
        mapaPanelLayout.setHorizontalGroup(
            mapaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timerP, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mapaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mapaPanelLayout.setVerticalGroup(
            mapaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mapaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(mapaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timerP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(mapaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        eventoPanel.setBackground(new java.awt.Color(0, 3, 5));

        javax.swing.GroupLayout eventoPanelLayout = new javax.swing.GroupLayout(eventoPanel);
        eventoPanel.setLayout(eventoPanelLayout);
        eventoPanelLayout.setHorizontalGroup(
            eventoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eventoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        eventoPanelLayout.setVerticalGroup(
            eventoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eventoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(eventoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        batallaPanel.setBackground(new java.awt.Color(0, 63, 65));
        batallaPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout batallaPanelLayout = new javax.swing.GroupLayout(batallaPanel);
        batallaPanel.setLayout(batallaPanelLayout);
        batallaPanelLayout.setHorizontalGroup(
            batallaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(batallaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        batallaPanelLayout.setVerticalGroup(
            batallaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(batallaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(batallaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        // TODO add your handling code here:
        menuPanel.setVisible(false);
        mapaPanel.setVisible(true);
        partida.empezar(mapaPanel);
        temporizador = new Timer(100, (ActionEvent e) -> {
            //accion cuando llega a cero
            sec++;
            if (sec == 60) {
                minute++;
                sec = 0;
            }
            timerP.setText(minute+"m"+sec+"s");
        });
    }//GEN-LAST:event_IniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    public Juego getPartida() {
        return partida;
    }

    public JLabel getBatallaLabel() {
        return batallaLabel;
    }

    public JPanel getBatallaPanel() {
        return batallaPanel;
    }

    public JLabel getEventoLabel() {
        return eventoLabel;
    }

    public JPanel getEventoPanel() {
        return eventoPanel;
    }

    public JLabel getMapaLabel() {
        return mapaLabel;
    }

    public JPanel getMapaPanel() {
        return mapaPanel;
    }

    public JLabel getMenuLabel() {
        return menuLabel;
    }

    public JPanel getMenuPanel() {
        return menuPanel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iniciar;
    private javax.swing.JLabel batallaLabel;
    private javax.swing.JPanel batallaPanel;
    private javax.swing.JLabel eventoLabel;
    private javax.swing.JPanel eventoPanel;
    private javax.swing.JLabel mapaLabel;
    private javax.swing.JPanel mapaPanel;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel timerP;
    // End of variables declaration//GEN-END:variables
}
