/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.*;
import SonidoEImagen.Imagen;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 
 * @author a22victorlr
 */
public class UI extends javax.swing.JFrame {
    private Juego partida = new Juego();
    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        
        colocarImagenes();
    }
    
    
private void colocarImagenes(){
    //Strings de dirección
    String menuDirec = SonidoEImagen.Imagen.getImageLink("Menu");
    String evtDirec = SonidoEImagen.Imagen.getImageLink("Evento");
    String batallaDirec = SonidoEImagen.Imagen.getImageLink("Batalla");
    String mapaDirec = SonidoEImagen.Imagen.getImageLink("Mapa");
    String inicDirec = SonidoEImagen.Imagen.getImageLink("Inicio");
    
    
    ImageIcon menu = new ImageIcon(menuDirec);
    ImageIcon menuRedimen = Imagen.redimensionarimagen(menu, menuLabel.getWidth(), menuLabel.getHeight());
    this.menuLabel.setIcon(menuRedimen);
    
    ImageIcon evento = new ImageIcon(evtDirec);
    ImageIcon eventoRedimen = Imagen.redimensionarimagen(evento, eventoLabel.getWidth(), eventoLabel.getHeight());
    this.eventoLabel.setIcon(eventoRedimen);
    
    ImageIcon batalla = new ImageIcon(batallaDirec);
    ImageIcon batallaRedimen = Imagen.redimensionarimagen(batalla, batallaLabel.getWidth(), batallaLabel.getHeight());
    this.batallaLabel.setIcon(batallaRedimen);
    
    ImageIcon mapa = new ImageIcon(mapaDirec);
    ImageIcon mapaRedimen = Imagen.redimensionarimagen(mapa, mapaLabel.getWidth(), mapaLabel.getHeight());
    this.mapaLabel.setIcon(mapaRedimen);
    
    ImageIcon inic = new ImageIcon(inicDirec);
    ImageIcon inicRedimen = Imagen.redimensionarimagen(inic, Iniciar.getWidth(), Iniciar.getHeight());
    this.Iniciar.setIcon(inicRedimen);
    
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        batallaPanel = new javax.swing.JPanel();
        batallaLabel = new javax.swing.JLabel();
        eventoPanel = new javax.swing.JPanel();
        eventoLabel = new javax.swing.JLabel();
        mapaPanel = new javax.swing.JPanel();
        Mazo = new javax.swing.JButton();
        mapaLabel = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        Iniciar = new javax.swing.JButton();
        menuLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(816, 639));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        batallaPanel.setBackground(new java.awt.Color(0, 63, 65));
        batallaPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        batallaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        batallaPanel.add(batallaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        getContentPane().add(batallaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, -1, -1));

        eventoPanel.setBackground(new java.awt.Color(0, 3, 5));
        eventoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        eventoPanel.add(eventoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        getContentPane().add(eventoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 600, -1, -1));

        mapaPanel.setBackground(new java.awt.Color(60, 63, 5));
        mapaPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        mapaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mazo.setText("jButton1");
        Mazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MazoActionPerformed(evt);
            }
        });
        mapaPanel.add(Mazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, -1, -1));
        mapaPanel.add(mapaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        getContentPane().add(mapaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, -1, -1));

        menuPanel.setBackground(new java.awt.Color(60, 3, 65));
        menuPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });
        menuPanel.add(Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 192, 56));
        menuPanel.add(menuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        getContentPane().add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        // TODO add your handling code here:
        menuPanel.setLocation(800, 1200);
        mapaPanel.setLocation(0, 0);
    }//GEN-LAST:event_IniciarActionPerformed

    private void MazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MazoActionPerformed
        // TODO add your handling code here:
        mapaPanel.setLocation(800, 0);
        eventoPanel.setLocation(0, 0);
        partida.mostrarMazo(eventoPanel);
    }//GEN-LAST:event_MazoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    public Juego getPartida() {
        return partida;
    }

    public JLabel getBatallaLabel() {
        return batallaLabel;
    }

    public JPanel getBatallaPanel() {
        return batallaPanel;
    }

    public JLabel getEventoLabel() {
        return eventoLabel;
    }

    public JPanel getEventoPanel() {
        return eventoPanel;
    }

    public JLabel getMapaLabel() {
        return mapaLabel;
    }

    public JPanel getMapaPanel() {
        return mapaPanel;
    }

    public JLabel getMenuLabel() {
        return menuLabel;
    }

    public JPanel getMenuPanel() {
        return menuPanel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iniciar;
    private javax.swing.JButton Mazo;
    private javax.swing.JLabel batallaLabel;
    private javax.swing.JPanel batallaPanel;
    private javax.swing.JLabel eventoLabel;
    private javax.swing.JPanel eventoPanel;
    private javax.swing.JLabel mapaLabel;
    private javax.swing.JPanel mapaPanel;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
