/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import SonidoEImagen.Imagen;
import javax.swing.ImageIcon;

/**
 
 * @author a22victorlr
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        
        colocarImagenes();
    }
    
    
private void colocarImagenes(){
    String menuDirec = SonidoEImagen.Imagen.getImageLink("Menu");
    ImageIcon menu = new ImageIcon(menuDirec);
    ImageIcon menuRedimen = Imagen.redimensionarimagen(menu, menuLabel.getWidth(), menuLabel.getHeight());
    this.menuLabel.setIcon(menuRedimen);
    /*
    String batallaDirec = SonidoEImagen.Imagen.getImageLink("Batalla");
    ImageIcon batalla = new ImageIcon(batallaDirec);
    ImageIcon batallaRedimen = Imagen.redimensionarimagen(batalla, menuLabel.getWidth(), menuLabel.getHeight());
    this.menuLabel.setIcon(batallaRedimen);
    
    String mapaDirec = SonidoEImagen.Imagen.getImageLink("Mapa");
    ImageIcon mapa = new ImageIcon(mapaDirec);
    ImageIcon mapaRedimen = Imagen.redimensionarimagen(mapa, menuLabel.getWidth(), menuLabel.getHeight());
    this.menuLabel.setIcon(mapaRedimen);*/
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        batallaPanel = new javax.swing.JPanel();
        mapaPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        batallaPanel.setBackground(new java.awt.Color(0, 63, 65));
        batallaPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        batallaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(batallaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, -1, -1));

        mapaPanel.setBackground(new java.awt.Color(60, 63, 5));
        mapaPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        mapaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(mapaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, -1, -1));

        menuPanel.setBackground(new java.awt.Color(60, 3, 65));
        menuPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        menuPanel.add(menuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));
        String menuDirec = SonidoEImagen.Imagen.getImageLink("Menu");
        ImageIcon menu = new ImageIcon(menuDirec);
        ImageIcon menuRedimen = Imagen.redimensionarimagen(menu, this.getWidth(), this.getHeight());
        this.menuLabel.setIcon(menuRedimen);

        jButton1.setText("jButton1");
        menuPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, -1, -1));

        getContentPane().add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel batallaPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel mapaPanel;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
